version: '3.8'
services:
  tesnemapi:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: mateuspalacio/tesnem-api:1.0
    container_name: tesnemapi
    restart: always
  tesnemapi2:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: mateuspalacio/tesnem-api:1.0
    container_name: tesnemapi2
    restart: always
  tesnemapi3:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: mateuspalacio/tesnem-api:1.0
    container_name: tesnemapi3
    restart: always
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - 80:80
      - 443:443
      - 22:22
    depends_on:
      - tesnemapi
      - tesnemapi2
      - tesnemapi3
    restart: always